import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Platform Architecture',
      collapsed: false,
      items: [
        'core/architecture/HLD',
        'core/architecture/DDD',
        'core/architecture/defense-readiness',
        'core/architecture/DR-BC',
      ],
    },
    {
      type: 'category',
      label: 'ADRs',
      collapsed: true,
      link: {type: 'doc', id: 'core/architecture/adr/adr-index'},
      items: [
        {type: 'autogenerated', dirName: 'core/architecture/adr'},
      ],
    },
    {
      type: 'doc',
      id: 'core/diagrams/gallery',
      label: 'Diagrams',
    },
    {
      type: 'category',
      label: 'API And Operations',
      collapsed: false,
      items: [
        'api/api-overview',
        'core/api-reference',
        'core/configuration-reference',
        'DEPLOYMENT_CHECKLIST',
        'PROVIDER_CONFIG',
        'core/performance-baseline',
        {
          type: 'category',
          label: 'Runbooks',
          items: [
            {type: 'autogenerated', dirName: 'core/runbooks'},
            'runbooks/48hr-teardown',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Platform Domains',
      collapsed: true,
      items: [
        'cspm/HLD_CSPM_Aggregator',
        'cspm/DDD_CSPM_Aggregator',
        'cspm/SCHEMA_REFERENCE',
      ],
    },
    {
      type: 'category',
      label: 'Security And Governance',
      collapsed: true,
      items: [
        'threat-models/remediation-and-ai-pipeline',
        'DIAGRAM_STYLE_GUIDE',
      ],
    },
    {
      type: 'category',
      label: 'Research',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'research'},
      ],
    },
  ],
};

export default sidebars;
