import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        'core/architecture/HLD',
        'core/architecture/DDD',
        'core/architecture/DR-BC',
      ],
    },
    {
      type: 'category',
      label: 'ADRs',
      collapsed: true,
      link: {type: 'doc', id: 'core/architecture/adr/adr-index'},
      items: [
        {type: 'autogenerated', dirName: 'core/architecture/adr'},
      ],
    },
    {
      type: 'doc',
      id: 'core/diagrams/gallery',
      label: 'Diagrams',
    },
    {
      type: 'doc',
      id: 'api/api-overview',
      label: 'API Reference',
    },
    {
      type: 'category',
      label: 'CSPM Aggregator',
      collapsed: true,
      items: [
        'cspm/HLD_CSPM_Aggregator',
        'cspm/DDD_CSPM_Aggregator',
        'cspm/SCHEMA_REFERENCE',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Reference',
          items: [
            'core/api-reference',
            'core/configuration-reference',
            'core/performance-baseline',
            'PROVIDER_CONFIG',
            'DEPLOYMENT_CHECKLIST',
          ],
        },
        {
          type: 'category',
          label: 'Runbooks',
          items: [
            {type: 'autogenerated', dirName: 'core/runbooks'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Security',
      collapsed: true,
      items: [
        'threat-models/remediation-and-ai-pipeline',
        'DIAGRAM_STYLE_GUIDE',
      ],
    },
    {
      type: 'category',
      label: 'Research',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'research'},
      ],
    },
  ],
};

export default sidebars;
