# Python CI Template for GitLab (using uv per DEV_GUIDE standards)
# Include in your repo: include: 'https://gitlab.com/lvonguyen/lvonguyen-group/portfolio/shared/ci-templates/python-ci.yml'

stages:
  - build
  - test
  - lint

variables:
  PYTHON_VERSION: "3.12"
  UV_CACHE_DIR: $CI_PROJECT_DIR/.uv-cache

.python-cache:
  cache:
    key: ${CI_COMMIT_REF_SLUG}-python
    paths:
      - .uv-cache/
      - .venv/

.uv-setup:
  before_script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.cargo/bin:$PATH"
    - uv venv
    - uv sync

build:
  stage: build
  image: python:${PYTHON_VERSION}-slim
  extends:
    - .python-cache
    - .uv-setup
  script:
    - uv pip list
    - echo "[+] Dependencies installed successfully"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  stage: test
  image: python:${PYTHON_VERSION}-slim
  extends:
    - .python-cache
    - .uv-setup
  script:
    - uv run pytest tests/ -v --cov=src --cov-report=xml --cov-report=term
  coverage: '/TOTAL.*\s+(\d+%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 7 days
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lint:
  stage: lint
  image: python:${PYTHON_VERSION}-slim
  extends:
    - .python-cache
    - .uv-setup
  script:
    - uv run ruff check .
    - uv run ruff format --check .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Optional: Type checking
typecheck:
  stage: lint
  image: python:${PYTHON_VERSION}-slim
  extends:
    - .python-cache
    - .uv-setup
  script:
    - uv run mypy src/
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      exists:
        - pyproject.toml
