#!/usr/bin/env bash
# copy-service-icons.sh — Copy official vendor SVGs from lvn-library into frontend/public/icons/services/
# Supports --dry-run to preview without copying.
set -euo pipefail

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

DEST="$REPO_ROOT/frontend/public/icons/services"
LIB="/Users/lvonguyen/repos/gh/lvn-library/icons"
AWS_SRC="$LIB/aws_icons_all/aws_icon_package_01302026/Architecture-Service-Icons_01302026"
AWS_RES="$LIB/aws_icons_all/aws_icon_package_01302026/Resource-Icons_01302026"
AZURE_SRC="$LIB/Azure_Public_Service_Icons/Icons"
GCP_SRC="$LIB/gcp-icons/docs/images"

copied=0
errors=0

copy_icon() {
  local src="$1" dst="$2"
  if [[ ! -f "$src" ]]; then
    echo "[!] MISSING: $src -> $dst"
    ((errors++)) || true
    return
  fi
  if $DRY_RUN; then
    echo "[DRY] cp $src -> $dst"
  else
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    echo "[+] $dst ($(wc -c < "$dst") bytes)"
  fi
  ((copied++)) || true
}

echo "=== AWS (50 icons) ==="
copy_icon "$AWS_SRC/Arch_Storage/48/Arch_Amazon-Simple-Storage-Service_48.svg"            "$DEST/aws/s3.svg"
copy_icon "$AWS_SRC/Arch_Compute/48/Arch_Amazon-EC2_48.svg"                                "$DEST/aws/ec2.svg"
copy_icon "$AWS_SRC/Arch_Databases/48/Arch_Amazon-RDS_48.svg"                              "$DEST/aws/rds.svg"
copy_icon "$AWS_SRC/Arch_Containers/48/Arch_Amazon-Elastic-Kubernetes-Service_48.svg"      "$DEST/aws/eks.svg"
copy_icon "$AWS_SRC/Arch_Compute/48/Arch_AWS-Lambda_48.svg"                                "$DEST/aws/lambda.svg"
copy_icon "$AWS_SRC/Arch_Networking-Content-Delivery/48/Arch_Amazon-Virtual-Private-Cloud_48.svg" "$DEST/aws/vpc.svg"
copy_icon "$AWS_SRC/Arch_Networking-Content-Delivery/48/Arch_Amazon-CloudFront_48.svg"     "$DEST/aws/cloudfront.svg"
copy_icon "$AWS_SRC/Arch_Databases/48/Arch_Amazon-DynamoDB_48.svg"                         "$DEST/aws/dynamodb.svg"
copy_icon "$AWS_SRC/Arch_Application-Integration/48/Arch_Amazon-Simple-Queue-Service_48.svg" "$DEST/aws/sqs.svg"
copy_icon "$AWS_SRC/Arch_Containers/48/Arch_Amazon-Elastic-Container-Service_48.svg"       "$DEST/aws/ecs.svg"
copy_icon "$AWS_SRC/Arch_Security-Identity/48/Arch_AWS-WAF_48.svg"                         "$DEST/aws/waf.svg"
copy_icon "$AWS_SRC/Arch_Security-Identity/48/Arch_Amazon-GuardDuty_48.svg"                "$DEST/aws/guardduty.svg"
copy_icon "$AWS_SRC/Arch_Analytics/48/Arch_Amazon-SageMaker_48.svg"                        "$DEST/aws/sagemaker.svg"
copy_icon "$AWS_SRC/Arch_Developer-Tools/48/Arch_AWS-CodePipeline_48.svg"                  "$DEST/aws/codepipeline.svg"
copy_icon "$AWS_SRC/Arch_Application-Integration/48/Arch_Amazon-Simple-Notification-Service_48.svg" "$DEST/aws/sns.svg"
copy_icon "$AWS_SRC/Arch_Security-Identity/48/Arch_AWS-Secrets-Manager_48.svg"             "$DEST/aws/secretsmanager.svg"
copy_icon "$AWS_SRC/Arch_Security-Identity/48/Arch_AWS-Key-Management-Service_48.svg"      "$DEST/aws/kms.svg"
copy_icon "$AWS_SRC/Arch_Security-Identity/48/Arch_AWS-Certificate-Manager_48.svg"         "$DEST/aws/acm.svg"
copy_icon "$AWS_SRC/Arch_Management-Tools/48/Arch_Amazon-CloudWatch_48.svg"                "$DEST/aws/cloudwatch.svg"
copy_icon "$AWS_SRC/Arch_Application-Integration/48/Arch_AWS-Step-Functions_48.svg"        "$DEST/aws/step-functions.svg"
copy_icon "$AWS_SRC/Arch_Networking-Content-Delivery/48/Arch_Amazon-API-Gateway_48.svg"    "$DEST/aws/api-gateway.svg"
copy_icon "$AWS_SRC/Arch_Analytics/48/Arch_Amazon-Kinesis_48.svg"                          "$DEST/aws/kinesis.svg"
copy_icon "$AWS_SRC/Arch_Analytics/48/Arch_AWS-Glue_48.svg"                                "$DEST/aws/glue.svg"
copy_icon "$AWS_SRC/Arch_Analytics/48/Arch_Amazon-Athena_48.svg"                           "$DEST/aws/athena.svg"
copy_icon "$AWS_SRC/Arch_Analytics/48/Arch_Amazon-Redshift_48.svg"                         "$DEST/aws/redshift.svg"
copy_icon "$AWS_SRC/Arch_Databases/48/Arch_Amazon-ElastiCache_48.svg"                      "$DEST/aws/elasticache.svg"
copy_icon "$AWS_RES/Res_Databases/Res_Amazon-DynamoDB_Amazon-DynamoDB-Accelerator_48.svg"  "$DEST/aws/dax.svg"
copy_icon "$AWS_SRC/Arch_Analytics/48/Arch_Amazon-Managed-Streaming-for-Apache-Kafka_48.svg" "$DEST/aws/msk.svg"
copy_icon "$AWS_SRC/Arch_Application-Integration/48/Arch_Amazon-EventBridge_48.svg"        "$DEST/aws/eventbridge.svg"
copy_icon "$AWS_SRC/Arch_Compute/48/Arch_AWS-App-Runner_48.svg"                            "$DEST/aws/apprunner.svg"
copy_icon "$AWS_SRC/Arch_Containers/48/Arch_Amazon-Elastic-Container-Registry_48.svg"      "$DEST/aws/ecr.svg"
copy_icon "$AWS_SRC/Arch_Compute/48/Arch_Amazon-Lightsail_48.svg"                          "$DEST/aws/lightsail.svg"
copy_icon "$AWS_SRC/Arch_Management-Tools/48/Arch_AWS-Systems-Manager_48.svg"              "$DEST/aws/ssm.svg"
copy_icon "$AWS_SRC/Arch_Management-Tools/48/Arch_AWS-Config_48.svg"                       "$DEST/aws/awsconfig.svg"
copy_icon "$AWS_SRC/Arch_Management-Tools/48/Arch_AWS-CloudFormation_48.svg"               "$DEST/aws/cloudformation.svg"
copy_icon "$AWS_SRC/Arch_Compute/48/Arch_AWS-Elastic-Beanstalk_48.svg"                     "$DEST/aws/elasticbeanstalk.svg"
copy_icon "$AWS_SRC/Arch_Analytics/48/Arch_Amazon-EMR_48.svg"                              "$DEST/aws/emr.svg"
copy_icon "$AWS_SRC/Arch_Business-Applications/48/Arch_Amazon-Quick-Suite_48.svg"          "$DEST/aws/quicksight.svg"
copy_icon "$AWS_SRC/Arch_Migration-Modernization/48/Arch_AWS-Transfer-Family_48.svg"       "$DEST/aws/transfer.svg"
copy_icon "$AWS_SRC/Arch_Storage/48/Arch_Amazon-FSx_48.svg"                                "$DEST/aws/fsx.svg"
copy_icon "$AWS_SRC/Arch_Storage/48/Arch_Amazon-EFS_48.svg"                                "$DEST/aws/efs.svg"
copy_icon "$AWS_SRC/Arch_Storage/48/Arch_AWS-Backup_48.svg"                                "$DEST/aws/backup.svg"
copy_icon "$AWS_SRC/Arch_Networking-Content-Delivery/48/Arch_Amazon-Route-53_48.svg"       "$DEST/aws/route53.svg"
copy_icon "$AWS_SRC/Arch_Networking-Content-Delivery/48/Arch_AWS-Global-Accelerator_48.svg" "$DEST/aws/globalaccelerator.svg"
copy_icon "$AWS_SRC/Arch_Networking-Content-Delivery/48/Arch_AWS-Transit-Gateway_48.svg"   "$DEST/aws/transitgateway.svg"
copy_icon "$AWS_SRC/Arch_Networking-Content-Delivery/48/Arch_AWS-PrivateLink_48.svg"       "$DEST/aws/privatelink.svg"
copy_icon "$AWS_SRC/Arch_Networking-Content-Delivery/48/Arch_AWS-Direct-Connect_48.svg"    "$DEST/aws/directconnect.svg"
copy_icon "$AWS_SRC/Arch_Compute/48/Arch_AWS-Outposts-servers_48.svg"                      "$DEST/aws/outposts.svg"
copy_icon "$AWS_SRC/Arch_Compute/48/Arch_AWS-Batch_48.svg"                                 "$DEST/aws/batch.svg"
copy_icon "$AWS_SRC/Arch_Databases/48/Arch_Amazon-Timestream_48.svg"                       "$DEST/aws/timestream.svg"

echo ""
echo "=== Azure (46 icons) ==="
copy_icon "$AZURE_SRC/compute/10023-icon-service-Kubernetes-Services.svg"                  "$DEST/azure/aks.svg"
copy_icon "$AZURE_SRC/storage/10086-icon-service-Storage-Accounts.svg"                     "$DEST/azure/blob-storage.svg"
copy_icon "$AZURE_SRC/databases/10130-icon-service-SQL-Database.svg"                       "$DEST/azure/sql-database.svg"
copy_icon "$AZURE_SRC/compute/10029-icon-service-Function-Apps.svg"                        "$DEST/azure/functions.svg"
copy_icon "$AZURE_SRC/networking/10061-icon-service-Virtual-Networks.svg"                   "$DEST/azure/vnet.svg"
copy_icon "$AZURE_SRC/web/10035-icon-service-App-Services.svg"                             "$DEST/azure/app-service.svg"
copy_icon "$AZURE_SRC/databases/10121-icon-service-Azure-Cosmos-DB.svg"                    "$DEST/azure/cosmos-db.svg"
copy_icon "$AZURE_SRC/compute/10104-icon-service-Container-Instances.svg"                  "$DEST/azure/container-instances.svg"
copy_icon "$AZURE_SRC/security/10248-icon-service-Azure-Sentinel.svg"                      "$DEST/azure/sentinel.svg"
copy_icon "$AZURE_SRC/monitor/00001-icon-service-Monitor.svg"                              "$DEST/azure/monitor.svg"
copy_icon "$AZURE_SRC/ai + machine learning/10166-icon-service-Machine-Learning.svg"       "$DEST/azure/ml.svg"
copy_icon "$AZURE_SRC/devops/10261-icon-service-Azure-DevOps.svg"                          "$DEST/azure/devops-pipeline.svg"
copy_icon "$AZURE_SRC/security/10245-icon-service-Key-Vaults.svg"                          "$DEST/azure/key-vault.svg"
copy_icon "$AZURE_SRC/iot/00039-icon-service-Event-Hubs.svg"                               "$DEST/azure/event-hubs.svg"
copy_icon "$AZURE_SRC/integration/10836-icon-service-Azure-Service-Bus.svg"                "$DEST/azure/service-bus.svg"
copy_icon "$AZURE_SRC/integration/02631-icon-service-Logic-Apps.svg"                       "$DEST/azure/logic-apps.svg"
copy_icon "$AZURE_SRC/devops/10042-icon-service-API-Management-Services.svg"               "$DEST/azure/api-management.svg"
copy_icon "$AZURE_SRC/web/10162-icon-service-Cognitive-Services.svg"                       "$DEST/azure/cognitive-services.svg"
copy_icon "$AZURE_SRC/management + governance/00011-icon-service-Compliance.svg"            "$DEST/azure/purview.svg"
copy_icon "$AZURE_SRC/analytics/10126-icon-service-Data-Factories.svg"                     "$DEST/azure/data-factory.svg"
copy_icon "$AZURE_SRC/databases/00606-icon-service-Azure-Synapse-Analytics.svg"            "$DEST/azure/synapse.svg"
copy_icon "$AZURE_SRC/databases/10137-icon-service-Cache-Redis.svg"                        "$DEST/azure/redis-cache.svg"
copy_icon "$AZURE_SRC/web/10073-icon-service-Front-Door-and-CDN-Profiles.svg"              "$DEST/azure/front-door.svg"
copy_icon "$AZURE_SRC/networking/10076-icon-service-Application-Gateways.svg"              "$DEST/azure/application-gateway.svg"
copy_icon "$AZURE_SRC/networking/10064-icon-service-DNS-Zones.svg"                         "$DEST/azure/dns-zones.svg"
copy_icon "$AZURE_SRC/networking/02422-icon-service-Bastions.svg"                          "$DEST/azure/bastion.svg"
copy_icon "$AZURE_SRC/networking/10084-icon-service-Firewalls.svg"                         "$DEST/azure/firewall.svg"
copy_icon "$AZURE_SRC/networking/01105-icon-service-Private-Link-Service.svg"              "$DEST/azure/private-link.svg"
copy_icon "$AZURE_SRC/monitor/00009-icon-service-Log-Analytics-Workspaces.svg"             "$DEST/azure/log-analytics.svg"
copy_icon "$AZURE_SRC/databases/10145-icon-service-Azure-Data-Explorer-Clusters.svg"       "$DEST/azure/data-explorer.svg"
copy_icon "$AZURE_SRC/web/10052-icon-service-SignalR.svg"                                  "$DEST/azure/signalr.svg"
copy_icon "$AZURE_SRC/web/01007-icon-service-Static-Apps.svg"                              "$DEST/azure/static-web-apps.svg"
copy_icon "$AZURE_SRC/compute/10104-icon-service-Container-Instances.svg"                  "$DEST/azure/container-apps.svg"
copy_icon "$AZURE_SRC/iot/10182-icon-service-IoT-Hub.svg"                                  "$DEST/azure/iot-hub.svg"
copy_icon "$AZURE_SRC/other/02905-icon-service-Azure-Managed-Grafana.svg"                  "$DEST/azure/managed-grafana.svg"
copy_icon "$AZURE_SRC/monitor/00020-icon-service-Metrics.svg"                              "$DEST/azure/managed-prometheus.svg"
copy_icon "$AZURE_SRC/databases/02827-icon-service-Azure-Database-PostgreSQL-Server-Group.svg" "$DEST/azure/postgresql-flexible.svg"
copy_icon "$AZURE_SRC/databases/10122-icon-service-Azure-Database-MySQL-Server.svg"        "$DEST/azure/mysql-flexible.svg"
copy_icon "$AZURE_SRC/iot/10045-icon-service-Notification-Hubs.svg"                        "$DEST/azure/notification-hubs.svg"
copy_icon "$AZURE_SRC/compute/10031-icon-service-Batch-Accounts.svg"                       "$DEST/azure/batch.svg"
copy_icon "$AZURE_SRC/web/10073-icon-service-Front-Door-and-CDN-Profiles.svg"              "$DEST/azure/cdn.svg"
copy_icon "$AZURE_SRC/other/02361-icon-service-Backup-Vault.svg"                           "$DEST/azure/backup.svg"
copy_icon "$AZURE_SRC/management + governance/00017-icon-service-Recovery-Services-Vaults.svg" "$DEST/azure/site-recovery.svg"
copy_icon "$AZURE_SRC/management + governance/01710-icon-service-Arc-Machines.svg"          "$DEST/azure/arc.svg"
copy_icon "$AZURE_SRC/management + governance/10316-icon-service-Policy.svg"                "$DEST/azure/policy.svg"
copy_icon "$AZURE_SRC/management + governance/00004-icon-service-Cost-Management-and-Billing.svg" "$DEST/azure/cost-management.svg"
copy_icon "$AZURE_SRC/compute/10021-icon-service-Virtual-Machine.svg"                      "$DEST/azure/vm.svg"
copy_icon "$AZURE_SRC/identity/10224-icon-service-Active-Directory-Connect-Health.svg"     "$DEST/azure/active-directory.svg"

echo ""
echo "=== GCP (48 icons) ==="
copy_icon "$GCP_SRC/google_kubernetes_engine.svg"      "$DEST/gcp/gke.svg"
copy_icon "$GCP_SRC/cloud_storage.svg"                 "$DEST/gcp/cloud-storage.svg"
copy_icon "$GCP_SRC/cloud_sql.svg"                     "$DEST/gcp/cloud-sql.svg"
copy_icon "$GCP_SRC/cloud_functions.svg"               "$DEST/gcp/cloud-functions.svg"
copy_icon "$GCP_SRC/virtual_private_cloud.svg"         "$DEST/gcp/vpc-network.svg"
copy_icon "$GCP_SRC/cloud_run.svg"                     "$DEST/gcp/cloud-run.svg"
copy_icon "$GCP_SRC/bigquery.svg"                      "$DEST/gcp/bigquery.svg"
copy_icon "$GCP_SRC/security_command_center.svg"       "$DEST/gcp/chronicle.svg"
copy_icon "$GCP_SRC/cloud_monitoring.svg"              "$DEST/gcp/monitoring.svg"
copy_icon "$GCP_SRC/vertexai.svg"                      "$DEST/gcp/vertexai.svg"
copy_icon "$GCP_SRC/cloud_build.svg"                   "$DEST/gcp/cloudbuild.svg"
copy_icon "$GCP_SRC/pubsub.svg"                        "$DEST/gcp/pub-sub.svg"
copy_icon "$GCP_SRC/cloud_functions.svg"               "$DEST/gcp/cloud-functions-gen2.svg"
copy_icon "$GCP_SRC/cloud_tasks.svg"                   "$DEST/gcp/cloud-tasks.svg"
copy_icon "$GCP_SRC/cloud_scheduler.svg"               "$DEST/gcp/cloud-scheduler.svg"
copy_icon "$GCP_SRC/dataflow.svg"                      "$DEST/gcp/dataflow.svg"
copy_icon "$GCP_SRC/dataproc.svg"                      "$DEST/gcp/dataproc.svg"
copy_icon "$GCP_SRC/cloud_composer.svg"                "$DEST/gcp/composer.svg"
copy_icon "$GCP_SRC/memorystore.svg"                   "$DEST/gcp/memorystore.svg"
copy_icon "$GCP_SRC/filestore.svg"                     "$DEST/gcp/filestore.svg"
copy_icon "$GCP_SRC/artifact_registry.svg"             "$DEST/gcp/artifact-registry.svg"
copy_icon "$GCP_SRC/cloud_deploy.svg"                  "$DEST/gcp/cloud-deploy.svg"
copy_icon "$GCP_SRC/apigee_api_platform.svg"           "$DEST/gcp/apigee.svg"
copy_icon "$GCP_SRC/firestore.svg"                     "$DEST/gcp/firestore.svg"
copy_icon "$GCP_SRC/cloud_spanner.svg"                 "$DEST/gcp/spanner.svg"
copy_icon "$GCP_SRC/cloud_sql.svg"                     "$DEST/gcp/alloydb.svg"
copy_icon "$GCP_SRC/bigtable.svg"                      "$DEST/gcp/bigtable.svg"
copy_icon "$GCP_SRC/cloud_armor.svg"                   "$DEST/gcp/cloud-armor.svg"
copy_icon "$GCP_SRC/secret_manager.svg"                "$DEST/gcp/secret-manager.svg"
copy_icon "$GCP_SRC/key_management_service.svg"        "$DEST/gcp/kms.svg"
copy_icon "$GCP_SRC/certificate_manager.svg"           "$DEST/gcp/certificate-manager.svg"
copy_icon "$GCP_SRC/cloud_dns.svg"                     "$DEST/gcp/cloud-dns.svg"
copy_icon "$GCP_SRC/cloud_nat.svg"                     "$DEST/gcp/cloud-nat.svg"
copy_icon "$GCP_SRC/cloud_interconnect.svg"            "$DEST/gcp/cloud-interconnect.svg"
copy_icon "$GCP_SRC/cloud_cdn.svg"                     "$DEST/gcp/cloud-cdn.svg"
copy_icon "$GCP_SRC/anthos.svg"                        "$DEST/gcp/anthos.svg"
copy_icon "$GCP_SRC/binary_authorization.svg"          "$DEST/gcp/binary-authorization.svg"
copy_icon "$GCP_SRC/security_command_center.svg"       "$DEST/gcp/security-command-center.svg"
copy_icon "$GCP_SRC/cloud_logging.svg"                 "$DEST/gcp/cloud-logging.svg"
copy_icon "$GCP_SRC/trace.svg"                         "$DEST/gcp/cloud-trace.svg"
copy_icon "$GCP_SRC/looker.svg"                        "$DEST/gcp/looker.svg"
copy_icon "$GCP_SRC/data_catalog.svg"                  "$DEST/gcp/data-catalog.svg"
copy_icon "$GCP_SRC/data_loss_prevention_api.svg"      "$DEST/gcp/dlp.svg"
copy_icon "$GCP_SRC/cloud_healthcare_api.svg"          "$DEST/gcp/healthcare-api.svg"
copy_icon "$GCP_SRC/dialogflow.svg"                    "$DEST/gcp/dialogflow.svg"
copy_icon "$GCP_SRC/document_ai.svg"                   "$DEST/gcp/document-ai.svg"
copy_icon "$GCP_SRC/cloud_translation_api.svg"         "$DEST/gcp/translation.svg"
copy_icon "$GCP_SRC/cloud_vision_api.svg"              "$DEST/gcp/vision-ai.svg"
copy_icon "$GCP_SRC/identity_and_access_management.svg" "$DEST/gcp/iam-admin.svg"

echo ""
echo "=== Summary ==="
echo "Copied: $copied"
echo "Errors: $errors"
if $DRY_RUN; then
  echo "(dry run — no files were written)"
fi
