package terminal

// MockOutputs provides realistic demo output when cloud CLIs are not installed.
// Keys are generated by mockKey(): binary + first 1-2 non-flag args.
var MockOutputs = map[string]string{
	// --- AWS ---
	"aws s3 ls": `2026-01-15 09:23:41 aegis-audit-logs-prod
2026-02-01 14:05:22 aegis-config-snapshots
2026-02-18 08:30:00 aegis-terraform-state
2026-03-01 11:42:17 ns-product-search-assets-prd
2026-03-05 16:15:33 mr-payment-gateway-logs-prd
2026-03-10 07:55:01 pl-data-warehouse-exports`,

	"aws sts get-caller-identity": `{
    "UserId": "AROA3XFRBF23COLMFHKGZ:aegis-readonly-session",
    "Account": "431330216246",
    "Arn": "arn:aws:sts::431330216246:assumed-role/AegisReadOnlyRole/aegis-readonly-session"
}`,

	"aws ec2 describe-instances": `{
    "Reservations": [
        {
            "Instances": [
                {
                    "InstanceId": "i-0a1b2c3d4e5f67890",
                    "InstanceType": "t3.medium",
                    "State": {"Name": "running"},
                    "Tags": [{"Key": "Name", "Value": "aegis-api-prod-1"}],
                    "PrivateIpAddress": "10.0.1.42",
                    "LaunchTime": "2026-03-20T08:00:00Z"
                },
                {
                    "InstanceId": "i-0b2c3d4e5f678901a",
                    "InstanceType": "t3.small",
                    "State": {"Name": "running"},
                    "Tags": [{"Key": "Name", "Value": "aegis-worker-prod-1"}],
                    "PrivateIpAddress": "10.0.2.18",
                    "LaunchTime": "2026-03-20T08:05:00Z"
                }
            ]
        }
    ]
}`,

	"aws iam list-roles": `{
    "Roles": [
        {"RoleName": "AegisReadOnlyRole", "Arn": "arn:aws:iam::431330216246:role/AegisReadOnlyRole", "CreateDate": "2026-01-15T10:00:00Z"},
        {"RoleName": "AegisCrossAccountReader", "Arn": "arn:aws:iam::431330216246:role/AegisCrossAccountReader", "CreateDate": "2026-02-01T14:30:00Z"},
        {"RoleName": "ECSTaskExecutionRole", "Arn": "arn:aws:iam::431330216246:role/ECSTaskExecutionRole", "CreateDate": "2026-03-01T09:00:00Z"}
    ]
}`,

	"aws securityhub get-findings": `{
    "Findings": [
        {
            "Id": "arn:aws:securityhub:us-east-1:431330216246:finding/abc123",
            "Title": "S3 bucket does not have server-side encryption enabled",
            "Severity": {"Label": "HIGH"},
            "Compliance": {"Status": "FAILED"},
            "Resources": [{"Id": "arn:aws:s3:::ns-product-search-assets-prd"}],
            "CreatedAt": "2026-03-22T14:30:00Z"
        },
        {
            "Id": "arn:aws:securityhub:us-east-1:431330216246:finding/def456",
            "Title": "IAM policy allows full administrative privileges",
            "Severity": {"Label": "CRITICAL"},
            "Compliance": {"Status": "FAILED"},
            "Resources": [{"Id": "arn:aws:iam::431330216246:policy/LegacyAdminPolicy"}],
            "CreatedAt": "2026-03-21T09:15:00Z"
        }
    ]
}`,

	"aws organizations list-accounts": `{
    "Accounts": [
        {"Id": "431330216246", "Name": "lvn-personal", "Status": "ACTIVE", "Email": "aws-personal@lvonguyen.io"},
        {"Id": "831926608679", "Name": "haea-security", "Status": "ACTIVE", "Email": "security@haeaus.com"},
        {"Id": "607322091941", "Name": "kna-prod", "Status": "ACTIVE", "Email": "aws-kna@haeaus.com"}
    ]
}`,

	// --- GCloud ---
	"gcloud projects list": `PROJECT_ID             NAME                   PROJECT_NUMBER
lvn-dev-483106         lvn-dev                483106
aegis-prod-291847      aegis-prod             291847
ns-analytics-573920    ns-analytics           573920`,

	"gcloud compute instances list": `NAME                  ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP    STATUS
aegis-api-prod        us-central1-a  e2-medium                   10.128.0.2   34.68.142.91   RUNNING
aegis-worker-prod     us-central1-b  e2-small                    10.128.0.3                  RUNNING
puppygraph-demo       us-east1-b     e2-standard-2               10.142.0.4   35.231.18.77   RUNNING`,

	"gcloud iam roles list": `ROLE_ID                          TITLE                            STAGE
roles/viewer                     Viewer                           GA
roles/editor                     Editor                           GA
roles/owner                      Owner                            GA
roles/securityReviewer           Security Reviewer                GA
roles/iam.securityAdmin          Security Admin                   GA`,

	// --- Azure ---
	"az account list": `[
  {
    "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    "name": "sub-lvn-dev",
    "state": "Enabled",
    "isDefault": true,
    "tenantId": "f0e1d2c3-b4a5-6789-0fed-cba987654321"
  },
  {
    "id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
    "name": "HMGNA-Security",
    "state": "Enabled",
    "isDefault": false,
    "tenantId": "f0e1d2c3-b4a5-6789-0fed-cba987654321"
  }
]`,

	"az vm list": `[
  {
    "name": "aegis-jumpbox",
    "resourceGroup": "aegis-prod-rg",
    "location": "eastus",
    "powerState": "VM running",
    "vmSize": "Standard_B2s"
  }
]`,

	"az security alert list": `[
  {
    "alertDisplayName": "Suspicious authentication activity",
    "severity": "High",
    "status": "Active",
    "compromisedEntity": "user@haeaus.com",
    "startTimeUtc": "2026-03-24T18:30:00Z"
  }
]`,

	// --- kubectl ---
	"kubectl get pods": `NAMESPACE     NAME                                    READY   STATUS    RESTARTS   AGE
aegis         aegis-api-7d4f8b6c9d-x2k5j              1/1     Running   0          3d
aegis         aegis-worker-5c8e9f7a3b-m4n2p            1/1     Running   0          3d
aegis         aegis-redis-0                             1/1     Running   0          7d
kube-system   coredns-5d78c9869d-9k2lm                  1/1     Running   0          14d
kube-system   metrics-server-6d684c7b5d-7h3jn           1/1     Running   0          14d`,

	"kubectl get nodes": `NAME                          STATUS   ROLES    AGE   VERSION
ip-10-0-1-42.ec2.internal    Ready    <none>   30d   v1.29.3
ip-10-0-2-18.ec2.internal    Ready    <none>   30d   v1.29.3
ip-10-0-3-55.ec2.internal    Ready    <none>   14d   v1.29.3`,

	"kubectl get namespaces": `NAME              STATUS   AGE
aegis             Active   30d
default           Active   45d
kube-system       Active   45d
monitoring        Active   28d
ingress-nginx     Active   28d`,

	"kubectl get deployments": `NAMESPACE   NAME           READY   UP-TO-DATE   AVAILABLE   AGE
aegis       aegis-api      2/2     2            2           3d
aegis       aegis-worker   1/1     1            1           3d
monitoring  prometheus     1/1     1            1           28d
monitoring  grafana        1/1     1            1           28d`,

	"kubectl get services": `NAMESPACE   NAME           TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)          AGE
aegis       aegis-api      LoadBalancer   10.100.0.42    34.68.142.91   443:31443/TCP    3d
aegis       aegis-redis    ClusterIP      10.100.0.88    <none>         6379/TCP         7d
default     kubernetes     ClusterIP      10.100.0.1     <none>         443/TCP          45d`,

	"kubectl cluster-info": `Kubernetes control plane is running at https://ABCDEF1234.gr7.us-east-1.eks.amazonaws.com
CoreDNS is running at https://ABCDEF1234.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy`,

	// --- Terraform ---
	"terraform state list": `module.network.aws_vpc.main
module.network.aws_subnet.private[0]
module.network.aws_subnet.private[1]
module.network.aws_nat_gateway.main
module.database.aws_db_instance.main
module.redis.aws_elasticache_cluster.main
module.compute.aws_ecs_cluster.main
module.compute.aws_ecs_service.api
module.compute.aws_ecs_task_definition.api
module.compute.aws_lb.main
module.secrets.aws_secretsmanager_secret.jwt`,

	"terraform output": `api_url = "https://api-personal.lvonguyen.com"
db_endpoint = "aegis-db.c1234567.us-east-1.rds.amazonaws.com:5432"
redis_endpoint = "aegis-redis.abc123.0001.use1.cache.amazonaws.com:6379"
ecs_cluster = "aegis-prod"
alb_dns = "aegis-alb-1234567890.us-east-1.elb.amazonaws.com"`,

	"terraform workspace list": `  default
* personal
  haea-dev
  haea-staging`,

	"terraform version": `Terraform v1.7.5
on darwin_arm64

+ provider registry.terraform.io/hashicorp/aws v5.40.0
+ provider registry.terraform.io/hashicorp/random v3.6.0`,

	// --- Trivy ---
	"trivy image": `aegis-api:latest (alpine 3.19.1)

Total: 3 (HIGH: 2, CRITICAL: 1)

┌─────────────────┬───────────────┬──────────┬───────────────────┬───────────────┐
│     Library      │ Vulnerability │ Severity │ Installed Version │ Fixed Version │
├─────────────────┼───────────────┼──────────┼───────────────────┼───────────────┤
│ libcrypto3       │ CVE-2024-1234 │ CRITICAL │ 3.1.4-r1          │ 3.1.4-r5      │
│ libssl3          │ CVE-2024-5678 │ HIGH     │ 3.1.4-r1          │ 3.1.4-r5      │
│ busybox          │ CVE-2024-9012 │ HIGH     │ 1.36.1-r15        │ 1.36.1-r17    │
└─────────────────┴───────────────┴──────────┴───────────────────┴───────────────┘`,

	// --- aegis (internal CLI) ---
	"aegis status": `Cloud Aegis Platform Status
═══════════════════════════════════════
API Server:     HEALTHY  (v2.4.1, uptime 3d 14h)
Database:       HEALTHY  (PostgreSQL 16.2, 9.5K findings)
Redis:          HEALTHY  (7.2.4, 142 cached entries)
Graph Engine:   DEGRADED (PuppyGraph v0.113, schema pending)
SSE Channel:    ACTIVE   (3 subscribers)
Ticket Provider: asana   (last sync 2m ago)

Tenants: 1 active | Accounts: 170 discovered | Findings: 9,547`,

	"aegis findings": `SEVERITY   COUNT   TREND
─────────────────────────
CRITICAL     847   ▲ +12
HIGH        2,341   ▼ -8
MEDIUM      3,892   ─
LOW         2,467   ▲ +3
─────────────────────────
TOTAL       9,547

Top resources: S3 (1,204), IAM (987), EC2 (834), RDS (612)`,

	"aegis compliance": `FRAMEWORK          SCORE    STATUS
───────────────────────────────────
CIS AWS 2.0        78.4%   PARTIAL
SOC 2 Type II      82.1%   PARTIAL
PCI DSS 4.0        71.3%   FAILING
NIST 800-53        85.7%   PARTIAL
ISO 27001          80.2%   PARTIAL
HIPAA              76.9%   PARTIAL
───────────────────────────────────
Overall posture: 79.1% (▲ +2.3% from last week)`,

	// --- Basic utilities ---
	"whoami":   "aegis-operator",
	"hostname": "aegis-terminal-prod-1",
	"date":     "Tue Mar 25 14:32:07 UTC 2026",
	"uptime":   " 14:32:07 up 3 days, 14:22,  0 users,  load average: 0.42, 0.38, 0.35",
}
